name: Deploy Next.js App

on:
  push:
    branches: [main] # 또는 master 브랜치

jobs:
  build-and-deploy:
    runs-on: self-hosted # 중요: self-hosted 러너 사용

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Next.js에 맞는 Node.js 버전 선택
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          # 필요한 환경 변수 설정
          NODE_ENV: production

      - name: Deploy to production directory
        run: |
          # 홈서버의 배포 디렉토리로 파일 복사
          mkdir -p /path/to/production/directory
          cp -R .next /path/to/production/directory/
          cp -R public /path/to/production/directory/
          cp package.json /path/to/production/directory/
          cp next.config.mjs /path/to/production/directory/

      - name: Restart service
        run: |
          # PM2나 Systemd 등을 사용하여 서비스 재시작
          # 예: PM2 사용 시
          cd /path/to/production/directory
          pm2 restart develop-blog
